/// EduX School Management System
/// Fee management database tables
library;

import 'package:drift/drift.dart';
import 'student_tables.dart';
import 'academic_tables.dart';
import 'school_tables.dart';

/// Fee types table - fee category definitions
class FeeTypes extends Table {
  /// Primary key
  IntColumn get id => integer().autoIncrement()();

  /// Fee type name (e.g., "Tuition Fee", "Transport Fee")
  TextColumn get name => text().withLength(max: 50)();

  /// Description
  TextColumn get description => text().nullable()();

  /// Is this a monthly recurring fee
  BoolColumn get isMonthly => boolean().withDefault(const Constant(true))();

  /// Is this fee refundable
  BoolColumn get isRefundable => boolean().withDefault(const Constant(false))();

  /// Account code for accounting
  TextColumn get accountCode => text().nullable()();

  /// Is fee type active
  BoolColumn get isActive => boolean().withDefault(const Constant(true))();

  /// Whether this fee type should appear in the class-wide fee structure editor.
  /// Set to false for per-student fees like transport or stationery.
  BoolColumn get showInClassStructure =>
      boolean().withDefault(const Constant(true))();

  /// Display order
  IntColumn get displayOrder => integer().withDefault(const Constant(0))();

  /// Record creation timestamp
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Record update timestamp
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
}

/// Fee structures table - class-wise fee definitions
class FeeStructures extends Table {
  /// Primary key
  IntColumn get id => integer().autoIncrement()();

  /// Class foreign key
  IntColumn get classId =>
      integer().references(Classes, #id, onDelete: KeyAction.cascade)();

  /// Fee type foreign key
  IntColumn get feeTypeId =>
      integer().references(FeeTypes, #id, onDelete: KeyAction.cascade)();

  /// Fee amount
  RealColumn get amount => real()();

  /// Academic year
  TextColumn get academicYear => text()();

  /// Effective from date
  DateTimeColumn get effectiveFrom => dateTime()();

  /// Effective to date (null if current)
  DateTimeColumn get effectiveTo => dateTime().nullable()();

  /// Is currently active
  BoolColumn get isActive => boolean().withDefault(const Constant(true))();

  /// Record creation timestamp
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Record update timestamp
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
}

/// Invoices table - fee invoices
class Invoices extends Table {
  /// Primary key
  IntColumn get id => integer().autoIncrement()();

  /// Unique invoice number
  TextColumn get invoiceNumber => text().unique()();

  /// Student foreign key
  IntColumn get studentId =>
      integer().references(Students, #id, onDelete: KeyAction.cascade)();

  /// Invoice month (YYYY-MM format)
  TextColumn get month => text()();

  /// Academic year
  TextColumn get academicYear => text()();

  /// Total amount (sum of all fee items)
  RealColumn get totalAmount => real()();

  /// Discount amount (from concessions)
  RealColumn get discountAmount => real().withDefault(const Constant(0))();

  /// Net amount (total - discount)
  RealColumn get netAmount => real()();

  /// Amount paid so far
  RealColumn get paidAmount => real().withDefault(const Constant(0))();

  /// Balance amount (net - paid)
  RealColumn get balanceAmount => real()();

  /// Invoice status (pending, partial, paid, overdue)
  TextColumn get status => text().withDefault(const Constant('pending'))();

  /// Issue date
  DateTimeColumn get issueDate => dateTime()();

  /// Due date
  DateTimeColumn get dueDate => dateTime()();

  /// Last payment date
  DateTimeColumn get lastPaymentDate => dateTime().nullable()();

  /// Notes
  TextColumn get notes => text().nullable()();

  /// Generated by (user ID)
  IntColumn get generatedBy => integer().references(Users, #id)();

  /// Record creation timestamp
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Record update timestamp
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
}

/// Invoice items table - line items in an invoice
class InvoiceItems extends Table {
  /// Primary key
  IntColumn get id => integer().autoIncrement()();

  /// Invoice foreign key
  IntColumn get invoiceId =>
      integer().references(Invoices, #id, onDelete: KeyAction.cascade)();

  /// Fee type foreign key
  IntColumn get feeTypeId => integer().references(FeeTypes, #id)();

  /// Description (auto-filled from fee type name)
  TextColumn get description => text()();

  /// Original amount
  RealColumn get amount => real()();

  /// Discount on this item
  RealColumn get discount => real().withDefault(const Constant(0))();

  /// Net amount (amount - discount)
  RealColumn get netAmount => real()();

  /// Record creation timestamp
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

/// Payments table - payment transactions
class Payments extends Table {
  /// Primary key
  IntColumn get id => integer().autoIncrement()();

  /// Unique receipt number
  TextColumn get receiptNumber => text().unique()();

  /// Invoice foreign key
  IntColumn get invoiceId =>
      integer().references(Invoices, #id, onDelete: KeyAction.cascade)();

  /// Student foreign key (denormalized for quick access)
  IntColumn get studentId => integer().references(Students, #id)();

  /// Payment amount
  RealColumn get amount => real()();

  /// Payment mode (cash, bank_transfer, cheque, online)
  TextColumn get paymentMode => text()();

  /// Reference number (bank ref, cheque number, transaction ID)
  TextColumn get referenceNumber => text().nullable()();

  /// Bank name (for cheque/bank transfer)
  TextColumn get bankName => text().nullable()();

  /// Cheque date (for cheque payments)
  DateTimeColumn get chequeDate => dateTime().nullable()();

  /// Remarks/notes
  TextColumn get remarks => text().nullable()();

  /// Payment date
  DateTimeColumn get paymentDate => dateTime()();

  /// Received by (user ID)
  IntColumn get receivedBy => integer().references(Users, #id)();

  /// Is payment cancelled
  BoolColumn get isCancelled => boolean().withDefault(const Constant(false))();

  /// Cancellation reason
  TextColumn get cancellationReason => text().nullable()();

  /// Record creation timestamp
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Record update timestamp
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
}

/// Concessions table - student fee discounts
class Concessions extends Table {
  /// Primary key
  IntColumn get id => integer().autoIncrement()();

  /// Student foreign key
  IntColumn get studentId =>
      integer().references(Students, #id, onDelete: KeyAction.cascade)();

  /// Fee type foreign key (null means applies to all fees)
  IntColumn get feeTypeId => integer().nullable().references(FeeTypes, #id)();

  /// Discount type (percentage, fixed)
  TextColumn get discountType => text()();

  /// Discount value (percentage or fixed amount)
  RealColumn get discountValue => real()();

  /// Reason for concession
  TextColumn get reason => text().nullable()();

  /// Start date (from when concession applies)
  DateTimeColumn get startDate => dateTime()();

  /// End date (null if ongoing)
  DateTimeColumn get endDate => dateTime().nullable()();

  /// Is concession currently active
  BoolColumn get isActive => boolean().withDefault(const Constant(true))();

  /// Approved by (user ID)
  IntColumn get approvedBy => integer().references(Users, #id)();

  /// Record creation timestamp
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  /// Record update timestamp
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
}

/// Ad-hoc invoice items table - for custom invoice line items not tied to fee types
/// Allows generating invoices for ANY purpose (exam fees, special charges, etc.)
class AdHocInvoiceItems extends Table {
  /// Primary key
  IntColumn get id => integer().autoIncrement()();

  /// Invoice foreign key
  IntColumn get invoiceId =>
      integer().references(Invoices, #id, onDelete: KeyAction.cascade)();

  /// Description of the charge (e.g., "Special Exam Fee", "Late Fine", "Damage Fee")
  TextColumn get description => text().withLength(max: 200)();

  /// Amount for this item
  RealColumn get amount => real()();

  /// Item category/type for reporting (e.g., "exam", "fine", "misc", "activity")
  TextColumn get category => text().withDefault(const Constant('misc'))();

  /// Record creation timestamp
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}
